config/routes.rb
TheNetwork::Application.routes.draw do

  resources :the_posts

 resources :users
 resources :sessions, only: [:new, :create, :destroy]

  root  'the_directory#home'
  
  match '/post',    to: 'the_posts#index',        via: 'get'
  match '/help',    to: 'the_directory#help',    via: 'get'
  match '/about',   to: 'the_directory#about',   via: 'get'
  match '/contact', to: 'the_directory#contact', via: 'get'
  match '/music', to: 'the_directory#music', via: 'get'
  match '/film', to: 'the_directory#film', via: 'get'
  match '/literature', to: 'the_directory#literature', via: 'get'
  match '/photography', to: 'the_directory#photography', via: 'get'
  match '/pnd', to: 'the_directory#pnd', via: 'get'
  match '/dns', to: 'the_directory#dns', via: 'get'
  match '/invitation', to: 'the_directory#invitation', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get "the_directory/music"
  get "the_directory/film"
  get "the_directory/literature"
  get "the_directory/photography"
  get "the_directory/pnd"
  get "the_directory/dns"

  get "users/new"
  get "users/show"

  get "the_post/music"
  get "the_post/film"
  get "the_post/literature"
  get "the_post/photography"
  get "the_post/pnd"
  get "the_post/dns"

end

app/models/the_post.rb
class ThePost < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
 
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/the_browse_controller.rb
class TheBrowseController < ApplicationController
end

def music
end

def film
end

def literature
end

def photography
end

def pnd
end

def dns
end

app/controllers/the_directory_controller.rb
class TheDirectoryController < ApplicationController
end

def home
end

def help
end

def about
end

def contact
end

def music
end

def film
end

def literature
end

def photography
end

def pnd
end

def dns
end

app/controllers/the_posts_controller.rb
class ThePostsController < ApplicationController
  before_action :set_the_post, only: [:show, :edit, :update, :destroy]

  # GET /the_posts
  # GET /the_posts.json
  def index
    @the_posts = ThePost.all
  end

  # GET /the_posts/1
  # GET /the_posts/1.json
  def show
  end

  # GET /the_posts/new
  def new
    @the_post = ThePost.new
  end

  # GET /the_posts/1/edit
  def edit
  end

  # POST /the_posts
  # POST /the_posts.json
  def create
    @the_post = ThePost.new(the_post_params)

    respond_to do |format|
      if @the_post.save
        format.html { redirect_to @the_post, notice: 'The post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @the_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @the_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /the_posts/1
  # PATCH/PUT /the_posts/1.json
  def update
    respond_to do |format|
      if @the_post.update(the_post_params)
        format.html { redirect_to @the_post, notice: 'The post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @the_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /the_posts/1
  # DELETE /the_posts/1.json
  def destroy
    @the_post.destroy
    respond_to do |format|
      format.html { redirect_to the_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_the_post
      @the_post = ThePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def the_post_params
      params.require(:the_post).permit(:title, :body, :art)
    end

    def create
  @user = User.create( user_params )
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:user).permit(:avatar)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def posts
  	@posts = Posts.find(params[:id])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "The Canvi, bitch."
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/the_browse_helper.rb
module TheBrowseHelper
end

app/helpers/the_directory_helper.rb
module TheDirectoryHelper
end

app/helpers/the_posts_helper.rb
module ThePostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  
    <p> a @CoreyMKimball Production </p>

  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.twitter.com/CanviInc">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Canvi", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Music", music_path %></li>
          <li><%= link_to "Film", film_path %></li>
          <li><%= link_to "Literature", literature_path %></li>
          <li><%= link_to "Photography", photography_path %></li>
          <li><%= link_to "Painting & Drawing", pnd_path %><li>
          <li><%= link_to "Design & Sculpture", dns_path %><li>
          <% if signed_in? %>
            <li><%= link_to "Post", post_path %></li>
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/the_browse/dns.html.erb
<h1> dns_browse </h1>

app/views/the_browse/film.html.erb
<h1> film_browse </h1>

app/views/the_browse/literature.html.erb
<h1> literature_browse </h1>

app/views/the_browse/music.html.erb
<h1> music_browse </h1>

app/views/the_browse/photography.html.erb
<h1> photography_browse </h1>

app/views/the_browse/pnd.html.erb
<h1> pnd_browse </h1>

app/views/the_directory/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/the_directory/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Contact Corey directly at Corey@thecanvi.com</p>

app/views/the_directory/dns.html.erb
<div class="center hero-unit">
  <h1>#Design and #Sculpture</h1>

  <h2>
    This is the directory page for #design and #sculpture.  Here you will find all listings published by artists associated with design or sculpture.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviPnD" data-widget-id="448636654186549250"><a class="twitter-timeline" href="https://twitter.com/TheCanviDnS" data-widget-id="448637450705829888">Tweets by @TheCanviDnS</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



  </h3>


</div>

app/views/the_directory/film.html.erb
<div class="center hero-unit">
  <h1>#Film</h1>

  <h2>
    This is the directory page for #film.  Here you will find all listings published by artists associated with film.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviFilm" data-widget-id="445786861584146432">Tweets by @TheCanviFilm</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>




  </h3>


</div>

app/views/the_directory/home.html.erb
<div class="center hero-unit">
<body>
  <h1>Canvi</h1>

  <h2>
    This is the directory page.  This is our initial introductory version of our software.  These are listings published by artists which are broadcasted on our Twitter profiles.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, and design and sculpture.  Search individually per each different category above; or search here on the main page for an array of different category posts.  Please make your selection.  At this time you will find posts from other creative people interested in providing a service to others.  We're here to fasciliate the creative process by connecting others, by providing a tool for collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>

  </h3>


</div>

app/views/the_directory/invitation.html.erb
<% provide(:title, 'Help') %>
<h1>Request Your Invitation</h1>
<p>Send a tweet and we'll send you a link</p>

app/views/the_directory/literature.html.erb
<div class="center hero-unit">
  <h1>#Literature</h1>

  <h2>
    This is the directory page for #literature.  Here you will find all listings published by artists associated with literature.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviLit" data-widget-id="448562022884450304">Tweets by @TheCanviLit</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



  </h3>


</div>

app/views/the_directory/music.html.erb
<div class="center hero-unit">
  <h1>#Music</h1>

  <h2>
    This is the directory page for #music.  Here you will find all listings published by artists associated with music.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviMusic" data-widget-id="445783943338409984">Tweets by @TheCanviMusic</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


  </h3>


</div>

app/views/the_directory/photography.html.erb
<div class="center hero-unit">
  <h1>#Photography</h1>

  <h2>
    This is the directory page for #photography.  Here you will find all listings published by artists associated with photography.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviPhoto" data-widget-id="448635269567098880">Tweets by @TheCanviPhoto</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



  </h3>


</div>

app/views/the_directory/pnd.html.erb
<div class="center hero-unit">
  <h1>#Painting and #Drawing</h1>

  <h2>
    This is the directory page for #painting and #drawing.  Here you will find all listings published by artists associated with painting or drawing.  At the top you will see six different art categories: music, film, literature, photography, painting and drawing, design and sculpture.  Search above for your creative help.  Please select your interest.  These are posts for connecting with others, with intention on collaborating on a creative project, and ultimately creating what you love to create- cheers.
  </h2>
  <h3>
<a class="twitter-timeline" href="https://twitter.com/TheCanviPnD" data-widget-id="448636654186549250">Tweets by @TheCanviPnD</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



  </h3>


</div>

app/views/the_posts/_form.html.erb
<%= form_for(@the_post) do |f| %>
  <% if @the_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@the_post.errors.count, "error") %> prohibited this the_post from being saved:</h2>

      <ul>
      <% @the_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :art %><br>
    <%= f.text_field :art %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/the_posts/edit.html.erb
<h1>Editing the_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @the_post %> |
<%= link_to 'Back', the_posts_path %>

app/views/the_posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Art</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @the_posts.each do |the_post| %>
      <tr>
        <td><%= the_post.title %></td>
        <td><%= the_post.body %></td>
        <td><%= the_post.art %></td>
        <td><%= link_to 'Show', the_post %></td>
        <td><%= link_to 'Edit', edit_the_post_path(the_post) %></td>
        <td><%= link_to 'Destroy', the_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a New Post', new_the_post_path %>

app/views/the_posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>



<%= link_to 'Back', the_posts_path %>

app/views/the_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @the_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @the_post.body %>
</p>

<p>
  <strong>Art:</strong>
  <%= @the_post.art %>
</p>

<%= link_to 'Edit', edit_the_post_path(@the_post) %> |
<%= link_to 'Back', the_posts_path %>

app/views/users/new.html.erb
<% provide(:title, 'New Users') %>
<h1>New Users</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>